sudo: required
  
# Enable C++ support
language: cpp

# enable cache
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

# environment 
matrix:
  include:

    # Linux g++7
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
    # Linux g++8
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    
    ## OSX
    #- os: osx
    #  osx_image: xcode8
    #  env:
    #    - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

    # Linux clang++6.0
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0', 'g++-7']
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        #- CXXFLAGS=-std=c++1z

# install cmake 3.10
before_install:
  - eval "${MATRIX_EVAL}"
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh 
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ctest
