sudo: required

# distribution
dist: trusty
  
# Enable C++ support
language: cpp

# enable cache
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

# environment 
# ref 1: https://github.com/google/re2
matrix:
  include:
    
    # Linux g++-5
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    
    # Linux g++-6
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # Linux g++-7
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
    # Linux g++-8
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # Linux g++-9
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"
    
    # Linux clang++4
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0', 'g++-5']
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    
    # Linux clang++5
    - os: linux
      compiler: clang++
      addons:
        apt:
          packages: 
            - clang-5.0
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons: &clang50
    
    # Linux clang++6
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-6.0', 'g++-7']
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    # Linux clang++7
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'g++-7']
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    
    # Linux clang++8
    - os: linux
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-8']
          packages: ['clang-8', 'g++-8']
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    
    ## OSX
    #- os: osx
    #  osx_image: xcode10
    #  compiler: clang
    #  env:
    #    - CXX=clang++

# install cmake 3.10
before_install:
  - eval "${MATRIX_EVAL}"
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh 
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - env CTEST_OUTPUT_ON_FAILURE=1 ctest
